server {
  listen 80;

  location = /index.html {
    root /usr/share/nginx/html;
    add_header Cache-Control "no-store" always;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://civicops-api:8080;
  }
}
