package org.civicops.cases.service;

public enum CaseServiceType {
  FOOD_ASSISTANCE,
  HOUSING_ASSISTANCE,
  TRANSPORTATION,
  COUNSELING_REFERRAL,
  EMPLOYMENT_SUPPORT,
  EDUCATION_SUPPORT,
  FINANCIAL_ASSISTANCE,
  OTHER
}
