ALTER TABLE organization_membership DROP CONSTRAINT ck_membership_role;
ALTER TABLE organization_membership ADD CONSTRAINT ck_membership_role CHECK (role IN ('ORG_ADMIN','PROGRAM_MANAGER','GRANT_MANAGER','DONATION_MANAGER','VOLUNTEER_COORDINATOR','EVENT_COORDINATOR','CASE_MANAGER','CASE_WORKER','VOLUNTEER','VIEWER'));

CREATE TABLE client (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organization(id), external_reference_number VARCHAR(100), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, preferred_name VARCHAR(100), date_of_birth DATE, email VARCHAR(320), phone VARCHAR(50), address_line1 VARCHAR(250), address_line2 VARCHAR(250), city VARCHAR(120), state VARCHAR(120), postal_code VARCHAR(30), country VARCHAR(2), preferred_contact_method VARCHAR(30), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT uk_client_id_org UNIQUE(id,organization_id));
CREATE UNIQUE INDEX uk_client_org_external_ref ON client(organization_id,external_reference_number) WHERE external_reference_number IS NOT NULL;
CREATE INDEX idx_client_org_active ON client(organization_id,active); CREATE INDEX idx_client_org_email ON client(organization_id,lower(email)) WHERE email IS NOT NULL;

CREATE TABLE case_record (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organization(id), client_id UUID NOT NULL, case_number VARCHAR(100) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT, case_type VARCHAR(40) NOT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'OPEN', opened_date DATE NOT NULL, closed_date DATE, assigned_user_id UUID, program_name VARCHAR(200), intake_source VARCHAR(200), created_by_user_id UUID NOT NULL REFERENCES app_user(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT uk_case_id_org UNIQUE(id,organization_id), CONSTRAINT uk_case_number_org UNIQUE(organization_id,case_number), CONSTRAINT fk_case_client_org FOREIGN KEY(client_id,organization_id) REFERENCES client(id,organization_id), CONSTRAINT ck_case_status CHECK(status IN ('OPEN','IN_PROGRESS','ON_HOLD','CLOSED','CANCELLED')), CONSTRAINT ck_case_priority CHECK(priority IN ('LOW','NORMAL','HIGH','URGENT')), CONSTRAINT ck_case_type CHECK(case_type IN ('GENERAL_ASSISTANCE','HOUSING','FOOD_ASSISTANCE','EMPLOYMENT','EDUCATION','FINANCIAL_ASSISTANCE','COMMUNITY_SERVICES','OTHER')), CONSTRAINT ck_case_closed CHECK((status IN ('CLOSED','CANCELLED') AND closed_date IS NOT NULL) OR (status NOT IN ('CLOSED','CANCELLED') AND closed_date IS NULL)));
CREATE INDEX idx_case_org_status ON case_record(organization_id,status); CREATE INDEX idx_case_org_assigned ON case_record(organization_id,assigned_user_id); CREATE INDEX idx_case_org_client ON case_record(organization_id,client_id); CREATE INDEX idx_case_org_opened ON case_record(organization_id,opened_date);

CREATE TABLE case_note (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organization(id), case_id UUID NOT NULL, author_user_id UUID NOT NULL REFERENCES app_user(id), note_type VARCHAR(30) NOT NULL, content TEXT NOT NULL, private_note BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT fk_note_case_org FOREIGN KEY(case_id,organization_id) REFERENCES case_record(id,organization_id)); CREATE INDEX idx_note_case_created ON case_note(case_id,created_at);
CREATE TABLE case_task (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organization(id), case_id UUID NOT NULL, title VARCHAR(200) NOT NULL, description TEXT, assigned_user_id UUID, due_date DATE, status VARCHAR(20) NOT NULL DEFAULT 'OPEN', priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL', completed_at TIMESTAMPTZ, created_by_user_id UUID NOT NULL REFERENCES app_user(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT fk_task_case_org FOREIGN KEY(case_id,organization_id) REFERENCES case_record(id,organization_id), CONSTRAINT ck_task_status CHECK(status IN ('OPEN','IN_PROGRESS','COMPLETED','CANCELLED')), CONSTRAINT ck_task_priority CHECK(priority IN ('LOW','NORMAL','HIGH','URGENT'))); CREATE INDEX idx_task_case_status ON case_task(case_id,status); CREATE INDEX idx_task_org_due ON case_task(organization_id,due_date);
CREATE TABLE case_service_record (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organization(id), case_id UUID NOT NULL, service_type VARCHAR(40) NOT NULL, description TEXT, service_date DATE NOT NULL, quantity NUMERIC(19,2), unit VARCHAR(50), value_amount NUMERIC(19,2), provided_by_user_id UUID REFERENCES app_user(id), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0, CONSTRAINT fk_service_case_org FOREIGN KEY(case_id,organization_id) REFERENCES case_record(id,organization_id), CONSTRAINT ck_service_type CHECK(service_type IN ('FOOD_ASSISTANCE','HOUSING_ASSISTANCE','TRANSPORTATION','COUNSELING_REFERRAL','EMPLOYMENT_SUPPORT','EDUCATION_SUPPORT','FINANCIAL_ASSISTANCE','OTHER'))); CREATE INDEX idx_service_case_date ON case_service_record(case_id,service_date);
